ALTER TABLE organization_settings
ADD COLUMN IF NOT EXISTS term1_start_md VARCHAR(5),
ADD COLUMN IF NOT EXISTS term1_end_md VARCHAR(5),
ADD COLUMN IF NOT EXISTS term2_start_md VARCHAR(5),
ADD COLUMN IF NOT EXISTS term2_end_md VARCHAR(5),
ADD COLUMN IF NOT EXISTS term3_start_md VARCHAR(5),
ADD COLUMN IF NOT EXISTS term3_end_md VARCHAR(5);
